import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/share/navbar/Navbar";
import Footer from "@/share/footer/Footer";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import ReduxProvider from "@/components/reduxProvider/ReduxProvider";
import Sitebar from "@/components/sidebar/Sidebar";
import { Toaster } from "react-hot-toast";
import TokenProvider from "@/components/AuthProvider/TokenProvider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

async function getData() {
  const url = `${process.env.BASE_URL}/api/group-information/${process.env.GROUP_ID}`;
  let res = await fetch(url, {
    next: { revalidate: 300 },
  });
  const groupDetails = await res.json();
  return groupDetails;
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const groupDetails = await getData();
  metadata.title = groupDetails?.group_name;

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <ReduxProvider>
          <AuthProvider>
            <TokenProvider>
              <div>
                <div>
                  <Navbar groupDetails={groupDetails} />
                </div>
                <div className=" min-h-[70vh] pt-[90px]">{children}</div>
                <div>
                  <Footer groupDetails={groupDetails} />
                </div>
              </div>
              <Sitebar />
              <Toaster position="top-center" reverseOrder={false} />
            </TokenProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
