import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/share/navbar/Navbar";
import Footer from "@/share/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ONEDROB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>
          <div>
            <Navbar />
          </div>
          <div className=" min-h-[70vh] pt-[90px]">
            {children}
          </div>
          <div>
            <Footer />
          </div>
        </div>

      </body>
    </html>
  );
}
